services:
  webhook-queue-delay:
    build: https://github.com/lr-24/webhook-queue-delay.git
    ports:
      - "3304:5000"
    environment:
      - FLASK_APP=app.py
      - API_BASE_URL=http://192.168.1.50:8080  # Replace with your API server's IP and port
      - FIREFLY_API_KEY=your_api_key_here  # Replace with your actual API key
      - WEBHOOK_ID=123  # Replace with your actual webhook ID if needed
    restart: unless-stopped
